language: node_js
node_js:
- 8
install: true
addons:
  sauce_connect: true
  jwt:
    secure: secure: DKvmnWLsnh5h9YU3DDSBh8LjmxnQqihW8NdMeZwqS9rbea4f8oq88kg/Gdg83xaRyz3XvDoPOHVQCKnRHgn4nksel/9Rv7+rg2BXyDq0mx5Lk3RNXUjuhDbyMoa+YNJELqjU6Kp7sIakElDmbfUcWtvj8y0WFXNJBMYJ6tBQGHNM1YByoYf5AzScYyv2s9AU29qAOlpgdrQ7e8aXfxydKiO4EqfM1/zThgKp0vngYgFVk+a8XB1Mzu5mkjWBvSJrCVecC2N1RAQqQJ+WK9IfxQrOmj+MlZIVL1IF1oRP5nhJoxd61fNMWtPsONNnzUsR3j/kTGw0BMBMpslmPPPf9Sh/9orMPuFPAp03+xtmzX3qmwq4/hCxEgONJQJ2VlvXEUgkfXpalg2gTd7ZjStzBHrJAs+vK21ZApSLf7wnT3c2i7MyRmVmKynLoYCU3ZZUmjszPt/9kL1SYn3Qum5Pz6fCoAj9NZ/VBirh7fltN84diPOeWpoR8bO1Q0tBMnk119YPvGh0fzXptBaQRmi9yztdOArNnXWKNa52eEo+dOvFQwgJqsv8IqJ2k76fXP/oiLxgtdzf1+b8InpoDP8fh5JoucEO/11wuRcijZcq6ONQImr/tRcb/OfvfJhR9X62Yq8gwQKT+j2QZSZ+KzrCdDcq7w5C1WaR1Q4PcsXsM6o=
jobs:
  include:
  - stage: test
    script:
    - bash .travis/run_on_non_pull_requests.sh; fi
    after_success:
    - bash <(curl -s https://codecov.io/bash)
  - stage: npm release
    if: tag IS present
    node_js: '8'
    script: yarn build
    before_deploy:
    - cd dist
    deploy:
      provider: npm
      branch: deploy
      email: "$NPM_EMAIL"
      api_key: "$NPM_TOKEN"
      skip_cleanup: true
      on:
        tags: true
notifications:
  slack:
    secure: ljxoSUkCW24qqKGhNuXciaKgrGn6pWMng7HAWCwpiMIHc5MeEtkgU/3HwkzRmlSnptCz6YNhf2w61dTT/NluCVZo3zyjf06iVmY3I8tEm75jl+IBfj3xk9oE54vIMjyPmiGR3yZMdVRlvKFAQyPtsEvZK++4/WJHZJZ8ItYnvTa+3QqzofjLAXjAxj2Ch4Q+jqD3BMzaaK/ZJi5w8pMNHczjtyxreImBK38ElOLlBxeYP2HCe41XXWjA5sgGrn6kJwUvYsAlyp2rTviNnvsnKYOePQuTjnlLchgWgtyfYhhuVhNfm75hBCDN4IE6gRcP5p22B9r2cuCVfYdjhwrsBlG9FtRPZjyzUkYc/vTLdBnJKPVuqkVRmcok/daPMxs5d2kiXeZwttr6cHBljlRQQG8ulApO05KCJGaTX4DNyY1C+Z1b4ncuHcS2lCw2Do9CbnRiWGFVu2aFZ7lzvaAhX1VVULULX20ymQqkHtKOBZq1rDn+UsZf0MFKtTICkgjn5XqOBVULXkjOvcnTCyKY2znPuvVtIq+bqFVk3Z6U9E0Lb8/ussotYEfwE3NyEVgimIaiNiiRI/0F/u8Xdv2LAql8tfROzVP6IWKRlLeZliH3RRtGMVckQU+AIEshXBCko5DqiXERqCYQNMlWJnBWetXlszNqRCssNrrI89P3xQk=
